savageflow/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from forum import views

urlpatterns = [

    #главная
    path('', views.main_view, name='main'),

    #меню
    path('about.html', views.about_view, name='about'),
    path('contact.html', views.contact_view, name='contact'),

    #questions
    path('questions.html', views.questions_view, name='questions'),
    path('questions/<int:post_id>/', views.question_detail, name='question_detail'),
    path('delete_answer/<int:answer_id>/', views.delete_answer, name='delete_answer'),
    path('questions/<int:question_id>/edit/<int:answer_id>/', views.edit, name='edit'),
    path('answer/<int:post_id>/', views.answer_view, name='answer'),

    #add question
    path('post.html', views.post_view, name='post'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    content_html = models.TextField(blank=True, null=True)  # Добавленное поле для хранения отформатированного текста
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    
class Answer(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='answer_images/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"Answer to {self.post.title}"

forum/forms.py
from django import forms
from .models import Post, Answer

class PostForm(forms.ModelForm):
    content = forms.CharField(required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ('content','image')

forum/views.py
import sqlite3
from PIL import Image
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from .forms import PostForm, AnswerForm
from django.http import HttpResponse, HttpResponsePermanentRedirect, HttpResponseRedirect, HttpResponseNotFound
from .models import Post, Answer

#главная страница
def main_view(request):
    sort_by = request.GET.get('sort_by', '-created_at')  # По умолчанию сортируем по дате создания (новые вопросы сверху)
    search_query = request.GET.get('search', '')  # Получаем поисковый запрос из параметра 'search' или пустую строку, если параметр не указан
    questions = Post.objects.filter(title__icontains=search_query).order_by(sort_by)
    context = {'questions': questions, 'sort_by': sort_by, 'search_query': search_query}
    paginator = Paginator(questions, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)
    context['page'] = page
    return render(request, 'main.html', context)

#меню
def about_view(request):
    return render(request, 'about.html')

def contact_view(request):
    return render(request, 'contact.html')

#вопросы
def questions_view(request):
    return render(request, 'questions.html')

def question_detail(request, post_id):
    question = get_object_or_404(Post, pk=post_id)
    return render(request, 'question_detail.html', {'question': question})

def delete_answer(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if answer.is_deleted:
        answer.delete()
    else:
        answer.is_deleted = True
        answer.save()
    return redirect(reverse('question_detail', kwargs={'post_id': answer.post_id}))

def edit(request, question_id, answer_id):
    try:
        answer = Answer.objects.get(id=answer_id)
        if request.method == 'POST':
            answer.content = request.POST.get("content")
            answer.save()
            return redirect(reverse('question_detail', kwargs={'post_id': answer.post_id}))
        else:
            return render(request, 'edit.html', {'answer': answer})
    except Answer.DoesNotExist:
        return HttpResponseNotFound("<h2>Answer not found</h2>")

def answer_view(request, post_id):
    post = Post.objects.get(pk=post_id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, request.FILES)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.post = post
            answer.save()
            return redirect(reverse('question_detail', kwargs={'post_id': post_id}))
    else:
        form = AnswerForm()

    return render(request, 'answer.html', {'form': form, 'post': post})

#добавить вопрос
def post_view(request):
    search_query = request.GET.get('search', '')
    posts = Post.objects.filter(Q(title__icontains=search_query) | Q(content__icontains=search_query))

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            if 'image' in request.FILES:
                post.image = request.FILES['image']
            post.save()
            return redirect('main')
        else:
            print(form.errors)  # Вывод ошибок формы в консоль
            messages.error(request, 'Ошибка при создании поста.')  # Отображение сообщения об ошибке пользователю
    else:
        form = PostForm()

    return render(request, 'post.html', {'form': form, 'posts': posts})

forum/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="about">
        <h2>О нас</h2>
        <p>Мы команда разработчиков, работающая над проектом, который изменит цифровую музыку. Наша цель - создать уникальный продукт, который позволит пользователям легко создавать и редактировать музыку с помощью компьютера или мобильного устройства.</p>
        <p>Если у вас есть вопросы или предложения, пожалуйста, свяжитесь с нами по телефону или по электронной почте:</p>
        <ul>
            <li>Телефон: +7 (999) 123-45-67</li>
            <li>Электронная почта: vepsre@myproject.com</li>
        </ul>
    </div>

    <link rel="stylesheet" href="{% static 'about.css' %}">

{% endblock %}

forum/templates/answer.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {% comment %} Make Your answer {% endcomment %}

    <div class="your-answer">
      <h2>Your Answer</h2>
      <form method="post" action="{% url 'answer' question.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="editor-container" style="position: relative; width: 500px; height: 300px;">
          <div id="editor" class="form-input" style="background-color: white;"></div>
          <textarea id="id_content" name="content" style="display: none;"></textarea> 
          <div id="counter" style="position: absolute; bottom: 0; right: 0;">Characters: 0</div>
          <button type="submit" class="create-button" style="background-color: blue; color: white; font-size: 14px; margin-top: 10px;">Создать</button>
        </div>        
      </form>
    </div>

    {% comment %} Editor {% endcomment %}
    
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="{% static 'editor.js' %}"></script>
    
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'editor.css' %}">

{% endblock %}

forum/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <!-- Bootstrap CSS -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title %}SavageFlow{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    
</head>
<body>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- logo -->
    <div class="logo">
        <h1><a href="/">Savageflow</a></h1>
    </div>
    <link rel="stylesheet" type="text/css" href="{% static 'logo.css' %}">

    <!-- menu --> 
    <div id="navbar" class="navbar">
        <a href="{% url 'main' %}">Главная</a>
        <a href="{% url 'about' %}">О нас</a>
        <a href="{% url 'contact' %}">Контакты</a>
    </div>
    <link rel="stylesheet" type="text/css" href="{% static 'menu.css' %}">

    {% block content %}
    {% endblock %}
</body>
</html>

forum/templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="contact">
    <h1>Contact Us</h1>
    <p>Phone: 123-456-7890</p>
    <p>Email: info@example.com</p>
  </div>

  <link rel="stylesheet" href="{% static 'contact.css' %}">

{% endblock %}

forum/templates/edit.html
<!DOCTYPE html>
{% load static %}
<html lang='en'>
    <head>
        <meta charset="UTF-8">
    </head>
    <body class="container">

        <!-- Редактирование человека -->
        <form method="POST">
            <!-- Защита от хакинг аттак -->
            {% csrf_token %}
            <p>
                <label> Введите текст </label>
                <input type="text" name = "content" value = "{answer.content}"/>
            </p>
            <input type="submit" value="Сохранить">
        </form>

    </body>
</html>

forum/templates/footer.html
<footer class="footer">
    Licensed by egordeev
</footer>

<style>
/* Стили для футера */
.footer {
  position: fixed;
  right: 10px;
  bottom: 10px;
  color: black;
}
</style>

forum/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Фильтр по заголовку -->
<div class="search-container">
    <input type="text" id="filter-input">
    <button onclick="handleSearch()">Search</button>
</div>
<script src="{% static 'search_bar.js' %}"></script>
<link rel="stylesheet" href="{% static 'search_bar.css' %}">

<!-- ask buttoon -->
<div style="position: fixed; top: 180px; right: 140px; background-color: blue; padding: 10px;">
    <a href="{% url 'post' %}" id="addQuestionBtn" style="color: white; text-decoration: none;">Add question</a>
</div>

{% include 'footer.html' %}
{% include 'questions.html' with questions=questions %}

{% endblock %}

forum/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <meta charset="UTF-8">
  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  
  {% comment %} Форма {% endcomment %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% comment %}Заголовок{% endcomment %}
    <div class="form-field">
      <label for="id_title" class="form-label" style="display: block; margin-bottom: 10px;"><strong>Заголовок:</strong></label>
      <input type="text" name="title" id="id_title" class="form-input" style="width: 500px; height: 30px; margin-bottom: 10px;" required>
    </div>
    {% comment %}Содержание{% endcomment %}
    <div class="form-field">
      <label for="id_content" class="form-label" style="display: block; margin-bottom: 10px;"><strong>Содержание:</strong></label>
      <div id="editor" class="form-input" style="width: 500px; height: 100px; margin-bottom: 10px; background-color: white; resize: both; overflow: auto;"></div>
      <textarea name="content" id="id_content"  data-min-length="30" style="display: none;"></textarea>
      <button type="submit" class="create-button" style="background-color: blue; color: white; font-size: 14px; margin-top: 40px;">Создать</button>
    </div>
  </form>

  {% comment %} Editor {% endcomment %}

  <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
  <script src="{% static 'editor.js' %}"></script>
    
  <style>
    .ql-toolbar {
      width: 500px;
      background-color: #eaf6ff; /* Нежно голубой фон */
    }
    .ql-container {
      width: 500px;
    }
  </style>

  {% comment %} Картинки {% endcomment %}

  <div>
    <img src="../static/media/site_images/images.png" alt="Вопрос" class="question-image" style="position: absolute; top: 100px; right: 200px; width: 296px; height: 170px; background: transparent;">
  </div>
  
<style>
  body {
    margin-top: 5%;
  }
</style>

{% endblock %}

forum/templates/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="container">
    
    {% comment %} Show Questions {% endcomment %}
    
    <div class="question">
      <h2>Question:</h2>
      <h1 class="question-title">{{ question.title }}</h1>
      <p style="white-space: pre-line;">{{ question.content | safe }}</p>
      {% if question.image %}
        <img src="{{ question.image.url }}" alt="Question Image">
      {% endif %}
      <p class="timestamp">Asked at: {{ question.created_at }}</p>
    </div>
    
    {% comment %} Show Answers {% endcomment %}

    <div class="answers">
      <h2>Answers:</h2>
      {% for answer in question.answer_set.all %}
      <div class="answer">
        <p>{{ answer.content | safe }}</p>
        {% if answer.image %}
          <img src="{{ answer.image.url }}" alt="Answer Image">
        {% endif %}
        <p class="timestamp">Answered at: {{ answer.created_at }}</p>
        <a href="edit/{{answer.id}}" class="action-button">Изменить</a>
        <a href="{% url 'delete_answer' answer.id %}">Удалить</a>
      </div>
    {% endfor %}    
    </div>

    {% comment %} Make Your answer {% endcomment %}

    <div class="your_answer">
      <h2>Your Answer:</h2>
      <form method="post" action="{% url 'answer' question.id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="editor-container" style="position: relative; width: 500px; height: 300px;">
          <div id="editor" class="form-input" style="background-color: white;"></div>
          <textarea id="id_content" name="content" style="display: none;"></textarea> 
          <button type="submit" class="create-button" style="background-color: blue; color: white; font-size: 14px; margin-top: 10px;">Создать</button>
        </div>        
      </form>
    </div>

    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="{% static 'editor.js' %}"></script>
    
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'editor.css' %}">
    
  </div>

  <link rel="stylesheet" type="text/css" href="{% static 'question_detail.css' %}">
  
{% endblock %}

forum/templates/questions.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="container">

    {% comment %}Заголовок{% endcomment %}

    <div class="heading">
      <h1>All questions</h1>
      <p id="question-count">Total number of questions: {{ questions.count }}</p>
    
      {% comment %}Сортировка{% endcomment %}

      <div class="sort-options">
        <label>Sort by:</label>
        <select id="sort-by-select" onchange="handleSortByChange(this)">
          <option value="-created_at" {% if sort_by == '-created_at' %}selected{% endif %}>Newest</option>
          <option value="created_at" {% if sort_by == 'created_at' %}selected{% endif %}>Oldest</option>
        </select>
      </div>

      <script>
        function handleSortByChange(selectElement) {
          const selectedValue = selectElement.value;
          const urlParams = new URLSearchParams(window.location.search);
          urlParams.set('sort_by', selectedValue);
          window.location.search = urlParams.toString();
        }
      </script>

    </div>

    {% comment %}Вывод вопросов{% endcomment %}

    <div id="question-list">
      {% for question in page %}
        <div class="question">
          <h2 class="question-title"><a href="{% url 'question_detail' question.id %}">{{ question.title }}</a></h2>
          <p class="question-details">{{ question.content }}</p>
          <p class="timestamp">Asked at: {{ question.created_at }}</p>
        </div>
      {% endfor %}
    </div>

    {% comment %}Переключение страниц{% endcomment %}

    <div class="pagination">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
      {% endif %}
      
      <span class="current-page">{{ page.number }}</span>

      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
    </div>

  </div>

  <link rel="stylesheet" href="{% static 'questions.css' %}">

{% endblock %}